travis:
  secure:
    BINSTAR_TOKEN: tLwXRAMXCdNgVKexIXAhNODOcPQNPv1F0vRFSmC2e4bAYhzf8vBXkCXXIF1upsgj8J3WdLf8QLRK1ML6LidbS3ENk7M0YR5AQxrmxJw7Q/R6ByWSWD2SsbsmXEB0aBekRBm8HVYq3C1CYK3xRBVLDpU4BKEL0q/kk9gBm/aeM1y4H1vOFJT0ExZhLb+YQ+9Vc3Lx7CQ1rWeWaSQ8aZwHp3ttEaZ4aV6vgMHP1KXo53z8HuP3iq0vsLgIbCWt51NFXbuDbUo12/xQoyK1u3aJAzCKAocForI/pdS/TnGMMUcuM/M9i3JUC0KgTBXUh2A3+Op9DG8TdyVprBNNDXN47rlhYcr4HthphXWksdJivl6gUcgmT5R5pov01GEih2Hf5dpVsGPY3GKmrcxF/a90ni57myfd+TZ3SWMVS/BhsZ0MfPdsDeAS99SyEwfPZwougXcG0IuGLljv8Whm3lsqnHnCmsoCT/ejad12uACh/+Qf7d2HXqTqGnUQMgA5mHC+qRTwB8Cx04ScYYzvGOY4MVP4wB2uoXtIwj+jgBPIS5xwxYJ+Llug8S7aupe4th829nGG97neM8YNofeASSEP57gdxkIK2jGJYZxyBGJp/9Gz4IeEFBAdAMunFuNvX2nY7l4d37Wr1f9aFeMxUo9Kvl1rICh+7e+kSM59OwySOdc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
