travis:
  secure:
    BINSTAR_TOKEN: PqnoliA5zVs6QuDbAiPqYb5zflYoZBsOrfCe2e0t/gnz5cTxSwMKxd+sF9tOeeC1F/iiC3GZi4lNZ+0tweQTTWvU5yGZGtaknMdFw0Jhh6fQ80lfxm+fFgqFvu9Rxlx+Q5TWiQnwOQKcf2RQxBOmxNKuxfTQg2vUJvCpavL2gqJJm5/Q5WwRkxFxiQBiyVIBwJnqs35Vvx2quvPM7JIWFWTUj5Fkyixn3xZTulg0XIBK8qdRgCZ407pq7DY8dPFqgabY6J5azqZ/rKmO3UYwX8x750npz7cZa9U1zxjXqmsO2pxBI02CFWh9Og5qRzHo980PRLTiPmoBkXSPEaZxHgiR0xbR8rvbEr1PwvaWHplDZTp046T2p8RwH3m6peqU+ubnk9MUoiHNMr6hyT9mAphVLUkAG9I3HM/qEf9fTxTPK0RmsuOeYez4hXbbCtNbN6ATNSuSJ9vaK6pt4PUtBuKfHFNJXZY1rKmES8qqu5svsFBdouapthxkWEbdNc9LkQfiVdhF+CKxLPgVIhlV61rnlgeAzHhu+hH+kDTMMTx7oXGCG0vDC/hhDKBPyN4IV6zTfP8rYuRPVWPspOTkPkkts59Qe1RWoFLyW5IiVOBDNmW1FrY4u2oEqM3ax7h791FYNTk5nBma+t+SR4yDu+xsz8S2Xco77BolhW8Q8u0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
